# Site settings
title: Anamika
email: mail@anamika.com.au
url: http://arunraj.us
description: "Kerala Cuisine Australia"
baseurl: "/restaurant"

# Color settings
color:
  primary-dark: '#242f36'
  links: '#219ab3'

# Footer settings
footer: anamika.com.au

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
